version: "3.9"
services:
  rabbitmq:
    image: "rabbitmq:3.9.13-management-alpine"
    hostname: "rabbit"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - "RABBITMQ_DEFAULT_USER=ibsm"
      - "RABBITMQ_DEFAULT_PASS=ibsm"

  knowledge:
    image: nsp00/ibsm-knowledge
    build:
      context: ../
      dockerfile: src/Knowledge.API/Dockerfile
    restart: on-failure
    depends_on: 
      - rabbitmq
    ports:
      - "11000:80"
      - "11001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__Port=5672
      - RabbitMQ__VHost=/
      - RabbitMQ__UserName=ibsm
      - RabbitMQ__Password=ibsm
      - RabbitQueues__RegionActionRequiredRequests__QueueName=region_action_required_requests
      
  data:
    image: nsp00/ibsm-data
    build: 
      context: ../
      dockerfile: src/Data.API/Dockerfile
    restart: on-failure
    ports:
     - "11010:80"
     - "11011:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ExternalServices__KnowledgeServiceUri=http://knowledge:8080
      - NlManagers__0__Id=1
      - NlManagers__0__Region=Vienna
      - NlManagers__0__Host=nl-vienna-1
      - NlManagers__0__Name=nl-vienna-1
      - NlManagers__1__Id=2
      - NlManagers__1__Region=Linz
      - NlManagers__1__Host=nl-linz-1
      - NlManagers__1__Name=nl-linz-1
  
  agent:
    image: nsp00/ibsm-agent
    build: 
      context: ../
      dockerfile: src/Agent.API/Dockerfile
    restart: on-failure
    depends_on:
     - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__Port=5672
      - RabbitMQ__VHost=/
      - RabbitMQ__UserName=ibsm
      - RabbitMQ__Password=ibsm
      - RabbitQueues__RegionActionRequiredRequests__QueueName=region_action_required_requests
      - ExternalServices__ReasoningServiceUri=http://knowledge:8080
      - ExternalServices__TopologyServiceUri=http://data:8080
     
  nl-vienna-1:
    image: nsp00/ibsm-networklayer
    build: 
      context: ../
      dockerfile: src/NetworkLayer.API/Dockerfile
    restart: on-failure
    ports:
     - "11020:80"
     - "11021:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - Simulation__InitialCount=15
    volumes:
      - ../Datasets/IncreasingWorkloadSameAvailability.csv:/app/dataset.csv
  
  nl-linz-1:
    image: nsp00/ibsm-networklayer
    build: 
      context: ../
      dockerfile: src/NetworkLayer.API/Dockerfile
    restart: on-failure
    ports:
     - "11024:80"
     - "11025:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - Simulation__InitialCount=15
    volumes:
      - ../Datasets/IncreasingWorkloadSameAvailability.csv:/app/dataset.csv
      
networks:
  default:
    name: "ibsm"
