version: "3.9"

x-aws-vpc: "vpc-0dcd851c4be1653e1"

services:
  knowledge:
    x-aws-role:
      Version: '2012-10-17'
      Statement:
        - Effect: Allow
          Action: "sqs:SendMessage"
          Resource: "arn:aws:sqs:us-east-1:284766146002:region_action_required_requests"
    image: nsp00/ibsm-knowledge
    ports:
      - "80:80"
      - ${ECS_KNOWLEDGE_HTTP2_Port}:${ECS_KNOWLEDGE_HTTP2_Port}
    environment:
      - ASPNETCORE_ENVIRONMENT=ECS
      - ASPNETCORE_Kestrel:HTTP2_Port=${ECS_KNOWLEDGE_HTTP2_Port}
      - "SqsQueues__RegionActionRequiredRequestsQueue=https://sqs.us-east-1.amazonaws.com/284766146002/region_action_required_requests"
      
  data:
    image: nsp00/ibsm-data
    depends_on:
      - knowledge
      - nl-vienna-1
      - nl-linz-1
    ports:
      - ${ECS_DATA_HTTP2_Port}:${ECS_DATA_HTTP2_Port}
    environment:
      - ASPNETCORE_ENVIRONMENT=ECS
      - ASPNETCORE_Kestrel:HTTP2_Port=${ECS_DATA_HTTP2_Port}
      - ExternalServices__KnowledgeServiceUri=http://knowledge:${ECS_KNOWLEDGE_HTTP2_Port}
      - NlManagers__0__Id=1
      - NlManagers__0__Region=Vienna
      - NlManagers__0__Host=nl-vienna-1
      - NlManagers__0__HostSuffix=.ibsm.local
      - NlManagers__0__Port=${ECS_NLVIENNA1_HTTP2_Port}
      - NlManagers__0__Name=nl-vienna-1
      - NlManagers__1__Id=2
      - NlManagers__1__Region=Linz
      - NlManagers__1__Host=nl-linz-1
      - NlManagers__1__HostSuffix=.ibsm.local
      - NlManagers__1__Port=${ECS_NLLINZ1_HTTP2_Port}
      - NlManagers__1__Name=nl-linz-1
       
  nl-vienna-1:
    image: nsp00/ibsm-networklayer
    ports:
      - ${ECS_NLVIENNA1_HTTP2_Port}:${ECS_NLVIENNA1_HTTP2_Port}
    environment:
      - ASPNETCORE_ENVIRONMENT=ECS
      - ASPNETCORE_Kestrel:HTTP2_Port=${ECS_NLVIENNA1_HTTP2_Port}
      - NetworkObjects__0__Application=Application1
      - NetworkObjects__1__Application=Application1
      - NetworkObjects__2__Application=Application1
      - NetworkObjects__3__Application=Application1
      - NetworkObjects__4__Application=Application1
          
  nl-linz-1:
    image: nsp00/ibsm-networklayer
    ports:
     - ${ECS_NLLINZ1_HTTP2_Port}:${ECS_NLLINZ1_HTTP2_Port}
    environment:
      - ASPNETCORE_ENVIRONMENT=ECS
      - ASPNETCORE_Kestrel:HTTP2_Port=${ECS_NLLINZ1_HTTP2_Port}
      - NetworkObjects__0__Application=Application2
      - NetworkObjects__1__Application=Application2
      - NetworkObjects__2__Application=Application2
      - NetworkObjects__3__Application=Application2
      - NetworkObjects__4__Application=Application2
      - NetworkObjects__5__Application=Application2
      
networks:
  default:
    name: "ibsm"
