version: "3.9"
services:
  rabbitmq:
    image: "rabbitmq:3.9.13-management-alpine"
    hostname: "rabbit"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - "RABBITMQ_DEFAULT_USER=ibsm"
      - "RABBITMQ_DEFAULT_PASS=ibsm"

  knowledge:
    image: ibsm-knowledge
    build:
      context: ../
      dockerfile: src/Knowledge.API/Dockerfile
    restart: on-failure
    depends_on: 
      - rabbitmq
    ports:
      - "11000:80"
      - "11001:443"
    environment:
      #- ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Enforce_HTTP2=true
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__Port=5672
      - RabbitMQ__VHost=/
      - RabbitMQ__UserName=ibsm
      - RabbitMQ__Password=ibsm
      - RabbitQueues__ReasoningResponseQueue__QueueName=agent_event_queue
    volumes:
      - ${CERTIFICATE_BASE_PATH}:/https/
      
  data:
    image: ibsm-data
    build: 
      context: ../
      dockerfile: src/Data.API/Dockerfile
    restart: on-failure
    ports:
     - "11010:80"
     - "11011:443"
    environment:
      #- ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Enforce_HTTP2=true
      - NlManagers__0__Id=1
      - NlManagers__0__Region=Vienna
      - NlManagers__0__Uri=http://nl-vienna-1:80
      - NlManagers__0__Name=nl-vienna-1
      - NlManagers__1__Id=2
      - NlManagers__1__Region=Vienna
      - NlManagers__1__Uri=http://nl-vienna-2:80
      - NlManagers__1__Name=nl-vienna-2
      - NlManagers__2__Id=3
      - NlManagers__2__Region=Linz
      - NlManagers__2__Uri=http://nl-linz-1:80
      - NlManagers__2__Name=nl-linz-1
    volumes:
      - ${CERTIFICATE_BASE_PATH}:/https/
  
  agent:
    image: ibsm-agent
    build: 
      context: ../
      dockerfile: src/Agent.API/Dockerfile
    restart: on-failure
    depends_on:
     - rabbitmq
    environment:
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__Port=5672
      - RabbitMQ__VHost=/
      - RabbitMQ__UserName=ibsm
      - RabbitMQ__Password=ibsm
      - RabbitQueues__RegionActionRequiredRequests__QueueName=agent_event_queue
      - ExternalServices__ReasoningServiceUri=http://knowledge:80
      - ExternalServices__TopologyServiceUri=http://data:80
     
  nl-vienna-1:
    image: ibsm-networklayer
    build: 
      context: ../
      dockerfile: src/NetworkLayer.API/Dockerfile
    restart: on-failure
    ports:
     - "11020:80"
     - "11021:443"
    environment:
      #- ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Enforce_HTTP2=true
      - NetworkObjects__0__Application=Application1
      - NetworkObjects__1__Application=Application1
      - NetworkObjects__2__Application=Application1
      - NetworkObjects__3__Application=Application1
      - NetworkObjects__4__Application=Application1
    volumes:
      - ${CERTIFICATE_BASE_PATH}:/https/
     
  nl-vienna-2:
    image: ibsm-networklayer
    build: 
      context: ../
      dockerfile: src/NetworkLayer.API/Dockerfile
    restart: on-failure
    ports:
     - "11022:80"
     - "11023:443"
    environment:
      #- ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Enforce_HTTP2=true
      - NetworkObjects__0__Application=Application1
      - NetworkObjects__1__Application=Application1
      - NetworkObjects__2__Application=Application1
    volumes:
      - ${CERTIFICATE_BASE_PATH}:/https/
     
  nl-linz-1:
    image: ibsm-networklayer
    build: 
      context: ../
      dockerfile: src/NetworkLayer.API/Dockerfile
    restart: on-failure
    ports:
     - "11024:80"
     - "11025:443"
    environment:
      #- ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Enforce_HTTP2=true
      - NetworkObjects__0__Application=Application2
      - NetworkObjects__1__Application=Application2
      - NetworkObjects__2__Application=Application2
      - NetworkObjects__3__Application=Application2
      - NetworkObjects__4__Application=Application2
      - NetworkObjects__5__Application=Application2
    volumes:
      - ${CERTIFICATE_BASE_PATH}:/https/
      
networks:
  default:
    name: "ibsm"
